// Generated by CoffeeScript 1.6.2
(function() {
  var eslParser, parse_header_text, querystring;

  querystring = require('querystring');

  module.exports = eslParser = (function() {
    function eslParser(socket) {
      this.socket = socket;
      this.body_length = 0;
      this.buffer = "";
    }

    eslParser.prototype.capture_body = function(data) {
      var body;

      this.buffer += data;
      if (this.buffer.length < this.body_length) {
        return;
      }
      body = this.buffer.substring(0, this.body_length);
      this.buffer = this.buffer.substring(this.body_length);
      this.body_length = 0;
      this.process(this.headers, body);
      this.headers = {};
      return this.capture_headers('');
    };

    eslParser.prototype.capture_headers = function(data) {
      var header_end, header_text;

      this.buffer += data;
      header_end = this.buffer.indexOf("\n\n");
      if (header_end < 0) {
        return;
      }
      header_text = this.buffer.substring(0, header_end);
      this.buffer = this.buffer.substring(header_end + 2);
      this.headers = parse_header_text(header_text);
      if (this.headers["Content-Length"]) {
        this.body_length = this.headers["Content-Length"];
        return this.capture_body('');
      } else {
        this.process(this.headers);
        this.headers = {};
        return this.capture_headers('');
      }
    };

    eslParser.prototype.on_data = function(data) {
      if (exports.debug) {
        util.log("on_data(" + data + ")");
      }
      if (this.body_length > 0) {
        return this.capture_body(data);
      } else {
        return this.capture_headers(data);
      }
    };

    eslParser.prototype.on_end = function() {
      if (exports.debug) {
        util.log("Parser: end of stream");
        if (this.buffer.length > 0) {
          return util.log("Buffer is not empty, left over: " + this.buffer);
        }
      }
    };

    return eslParser;

  })();

  parse_header_text = function(header_text) {
    var header_lines, headers, line, name, _fn, _i, _len, _ref;

    if (exports.debug) {
      util.log("parse_header_text(" + header_text + ")");
    }
    header_lines = header_text.split("\n");
    headers = {};
    _fn = function(line) {
      var name, value, _ref;

      _ref = line.split(/: /, 2), name = _ref[0], value = _ref[1];
      return headers[name] = value;
    };
    for (_i = 0, _len = header_lines.length; _i < _len; _i++) {
      line = header_lines[_i];
      _fn(line);
    }
    if (((_ref = headers['Reply-Text']) != null ? _ref[0] : void 0) === '%') {
      for (name in headers) {
        headers[name] = querystring.unescape(headers[name]);
      }
    }
    return headers;
  };

}).call(this);
